# Generated by Django 4.2.1 on 2023-06-01 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='like_users',
            new_name='like_comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like_users',
            new_name='like_post',
        ),
    ]
